name: Create Release

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: get version w/o v
      run: |
         VERSION=${GITHUB_REF_NAME#v}
         echo "VERSION=$VERSION" >> $GITHUB_ENV
         echo "version is v ${VERSION}"

    - name: version bump
      run: |
         sed -i -e "s/version=0.0.1/version=${VERSION}/" metadata.txt

    - name: git archive
      run: |
         git archive --format=zip --prefix=archive/ --output "archive_v${VERSION}.zip" HEAD
         
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "archive_v${VERSION}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
