name: Create Archive

on:
  create:
    tags:
      - *

permissions:
  contents: write

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: GitHub Tag Name example
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"

    - name: Sed
      run: |
         sed -e "s/version=0.0.1/version=${{  github.ref_name }}/" metadata.txt
