name: Create Release

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: version bump
      run: |
         sed -i -e "s/version=0.0.1/version=${{GITHUB_REF_NAME#v}}/" metadata.txt

    - name: git archive
      run: |
         git archive --format=zip --prefix=archive/ --output "archive_${{GITHUB_REF_NAME}}.zip" HEAD
         
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "archive_${{GITHUB_REF_NAME}}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
