name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: version bump
      run: |
         VERSION=${GITHUB_REF_NAME#v}
         echo "version is ${VERSION}"
         sed -i -e "s/version=0.0.1/version=${VERSION}/" metadata.txt

    - name: commit
      run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add metadata.txt
         git commit --amend --no-edit

    - name: git archive
      run: |
         git archive --format=zip --prefix=archive/ --add-file=metadata.txt --output "archive_${{ github.ref_name }}.zip" HEAD
         
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "archive_${{ github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
