name: Create Archive

on:
  create:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: GitHub Tag Name example
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"

    - name: version bump
      run: |
         sed -e "s/version=0.0.1/version=${{  github.ref_name }}/" metadata.txt

    - name: git archive
      run: |
         git archive --format=zip --prefix=archive/ --output "archive${{  github.ref_name }}.zip" HEAD
         
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "archive${{  github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
